In [2]:
import scipy.io
import h5py
import numpy as np

file_path = "/media/fcheng/FINCH-Clustering/data/STL-10/data.mat"

with h5py.File(file_path, 'r') as f:
    data = f['data']
    data = np.array(data).T


In [4]:
from FINCH_Core.clustRank import clustRank
initial_rank = []
Affinity_, orig_dist, _ = clustRank(data, initial_rank)


In [10]:
print(np.unique(Affinity_.toarray()))
print(np.sum(Affinity_.toarray()==1))
print(np.sum(Affinity_.toarray()==2))

[0. 1. 2.]
39630
4122


In [11]:
print(orig_dist[:10, :10])

[[       inf 0.6395585  0.52154286 0.5995917  0.57061387 0.68708042
  0.61140867 0.60762769 0.7541009  0.63417293]
 [0.6395585         inf 0.43758539 0.59992377 0.56114794 0.66856209
  0.50293046 0.57253003 0.59112056 0.72892383]
 [0.52154286 0.43758539        inf 0.58955268 0.50857371 0.64967182
  0.48365688 0.49866503 0.59112766 0.68967681]
 [0.5995917  0.59992377 0.58955268        inf 0.64691814 0.55600859
  0.66732459 0.67594276 0.6516746  0.6172101 ]
 [0.57061387 0.56114794 0.50857371 0.64691814        inf 0.66848808
  0.53286641 0.54126342 0.67626273 0.64625852]
 [0.68708042 0.66856209 0.64967182 0.55600859 0.66848808        inf
  0.69943659 0.72947556 0.72084234 0.45242419]
 [0.61140867 0.50293046 0.48365688 0.66732459 0.53286641 0.69943659
         inf 0.59029245 0.6973638  0.71914899]
 [0.60762769 0.57253003 0.49866503 0.67594276 0.54126342 0.72947556
  0.59029245        inf 0.70757007 0.72642576]
 [0.7541009  0.59112056 0.59112766 0.6516746  0.67626273 0.72084234
  0.6973638 

In [13]:
from FINCH_Core.get_clust import get_clust
Group_ = get_clust(Affinity_, [], np.inf)


In [30]:
print(np.unique(Group_), Group_.shape)
print(Group_[-10:])

[   0    1    2 ... 2058 2059 2060] (13000,)
[1806  475 1437  435 1661  840   11 1272 1743  430]


In [15]:
from FINCH_Core.get_merge import get_merge
c, num_clust, mat = get_merge([], Group_, data)


In [16]:
print(mat[:10, :10])

[[0.04093142 0.15441199 1.23327896 0.65436242 0.93097696 0.24027635
  0.52146819 0.28421423 0.08741484 0.00656254]
 [0.78801213 0.38923053 0.17731755 0.11491592 0.62110606 3.36836135
  0.06537916 0.36890557 0.10829236 0.04893236]
 [0.30743476 0.11307178 0.35239838 0.30884921 1.03607747 0.79648317
  0.16686233 0.14079956 0.24026253 0.21062335]
 [0.74710247 1.33104843 0.34513118 0.98153604 0.45060413 0.71767141
  0.29718454 0.83767126 3.18700963 0.03520721]
 [0.07266629 0.18395681 0.19053651 0.10359657 3.17704082 0.23914292
  0.3092468  0.49075881 0.00897    0.03298206]
 [0.28023019 0.14312471 0.1274875  0.70268275 0.2183824  2.26531586
  0.58831347 0.49654616 1.38862363 0.04738321]
 [0.20141239 0.13563699 0.31446827 0.10387727 5.89049594 0.08737619
  0.06358969 0.30360839 0.30314005 0.4703034 ]
 [0.10085571 0.17027033 0.27665633 0.10256788 0.71235251 1.13755859
  0.06933954 0.10267043 0.27801215 0.03590233]
 [0.33960968 0.25821274 0.08292947 0.42589353 0.48099163 1.01381814
  0.49558241

In [17]:
print(c)

[   0    1    2 ... 1272 1743  430]


In [18]:
print(num_clust)

2061


In [19]:
if orig_dist is not None:
    min_sim = np.max(orig_dist[Affinity_.toarray() > 0])
exit_clust = np.inf
c_ = c

num_clust = [num_clust]
k = 1


In [20]:
min_sim

0.6136007848862834

In [21]:
Affinity_, orig_dist, _ = clustRank(mat, initial_rank)

In [23]:
print(np.unique(Affinity_.toarray()), Affinity_.shape)
print(np.sum(Affinity_.toarray()==1))
print(np.sum(Affinity_.toarray()==2))

[0. 1. 2.] (2061, 2061)
10776
354


In [24]:
print(orig_dist[:10, :10])

[[       inf 0.57020554 0.34715549 0.54640924 0.45227307 0.5638903
  0.49385701 0.42531884 0.5270326  0.60911207]
 [0.57020554        inf 0.3735681  0.53338803 0.49428935 0.60130091
  0.49653613 0.41764132 0.36996124 0.66195068]
 [0.34715549 0.3735681         inf 0.46403775 0.33449995 0.54082887
  0.32733167 0.11392679 0.42109048 0.61311633]
 [0.54640924 0.53338803 0.46403775        inf 0.59324109 0.49952246
  0.60456511 0.50567573 0.51367608 0.5718305 ]
 [0.45227307 0.49428935 0.33449995 0.59324109        inf 0.5858491
  0.41247874 0.34489644 0.47353556 0.6243358 ]
 [0.5638903  0.60130091 0.54082887 0.49952246 0.5858491         inf
  0.59761345 0.58617073 0.53692177 0.39754032]
 [0.49385701 0.49653613 0.32733167 0.60456511 0.41247874 0.59761345
         inf 0.45379513 0.52918829 0.66503308]
 [0.42531884 0.41764132 0.11392679 0.50567573 0.34489644 0.58617073
  0.45379513        inf 0.51272066 0.63868981]
 [0.5270326  0.36996124 0.42109048 0.51367608 0.47353556 0.53692177
  0.52918829 0

In [25]:
u = get_clust(Affinity_, orig_dist, min_sim)


In [28]:
print(np.unique(u), u.shape)
print(u[-10:])

[   0    1    2 ... 2058 2059 2060] (2061,)
[2051 2052 2053 2054 2055 2056 2057 2058 2059 2060]


In [54]:
A = Affinity_
od = orig_dist

In [55]:
if min_sim != np.inf:
    # ind = np.stack(np.where(orig_dist*A > min_sim), axis=0).T
    A = A.toarray()
    mask = orig_dist * A
    mask[np.isnan(mask)>0] = np.inf
    A[mask > min_sim] = 0
    #A = A.tocoo()

/home/fcheng/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in multiply
  after removing the cwd from sys.path.


In [56]:
A.shape
print(type(orig_dist))

<class 'numpy.ndarray'>


In [37]:
print(np.unique(A.toarray()), A.shape)
print(np.sum(A.toarray()==1))
print(np.sum(A.toarray()==2))

[0.] (2061, 2061)
0
0


In [57]:
(orig_dist*Affinity_.toarray())[:10, :10]

/home/fcheng/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in multiply
  """Entry point for launching an IPython kernel.


array([[nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., nan]])

In [50]:
Affinity_.toarray()[:10, :10]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])